# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trusts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact_num', models.CharField(max_length=250)),
                ('Street_Address', models.CharField(max_length=500)),
                ('Locality', models.CharField(max_length=250)),
            ],
        ),
    ]
